### ISSUE TITLE
router.prefix 全局设置的问题

### ISSUE THREAD

**Issue by Kpyu** [super2god/egg-shell-decorators#7]
![image](https://user-images.githubusercontent.com/5809621/51108570-9857da00-182d-11e9-99b1-00da0eac07d5.png)
这里是设置全局的router prefix，这地方个人觉得是不是可以优化一下，不作全局的设置，仅限于使用蛋壳提供的装饰器的设置URL的prefix，比如我如果想值对/api/v1下的所有路由使用蛋壳，不影响普通路由的设置，现在的蛋壳貌似是做不到的，作者是不是可以考虑优化一下这块，让蛋壳更加灵活

**Comment by super2god** [comment]
嗯嗯，新版本（v1.5.0）已经去除了全局路由前缀的配置了
