### ISSUE TITLE
新手好难上手吖，但是很好看很想用。还有api-docs而且用express....

### ISSUE THREAD

**Issue by jaling530** [super2god/egg-shell-decorators#9]
没有swagger2方便，但是这个好看很多，又可以避免太多入侵代码。但是对我这类新手，很难上手。不像swagger2网上那么多实战例子，而且都是融入传统构建的egg-example的例子。而这个都是按照官方的说明例子。

**Comment by super2god** [comment]
嗯嗯，后面会考虑保留router的方式，该项目会继续维护呢~
